# Basics of Python, Numpy


Ali Alp Gurer- aalp.gurer@gmail.com

This is a great source to learn basics for python or review the content.

The best practice is to create new cells from the + above and write down a similar exmaple on your own.



## Installation

https://www.anaconda.com/distribution, Check out the welcome email for more detailed infomation. If you are able to open this document, there should not be any problem.

## Python basics

### Writing a comment

In [1]:
# This is how you comment things out. Type '#' followed by your text

In [2]:
# Here is another example of a comment

In [3]:
# Now lets use comments

In [4]:
print(1 + 2) # Addition
print(1 - 2) # Subtraction
print(1 * 2) # Multiplication
print(1 / 2) # Division
print(10 % 3) # return the remainder
print(10 // 3) # return the quotient
print(2 ** 3) # number raised to the power

3
-1
2
0.5
1
3
8


### Type and type conversion

In [5]:
print(type(9))
print(type(9.0))
print(type(1+3.33))

<class 'int'>
<class 'float'>
<class 'float'>


### Variables 

- Varialbes are assigned with the variable name on the left, and the value on the right of the equals sign. 
- Variables must be assigned before they can be used.
- Can be reassigned any time
- Variable name must start with a letter or underscore, cannot start with a number. Case sensitive.
- Wrong examples: 2cats, hey@you

In [7]:
num_1 = 10
num_2 = 20
print(num_1 + num_2)
print(num_1 * num_2)
num_2 = 30
print(num_2)
Num_2 = 40
print(num_2, Num_2)

30
200
30
30 40


### Data Types

- bool : True or False
- int: an integer
- str: a sequence of Unicode characters, like "friday"
- list: an ordered sequence of values of other data types
- dict: a collection of key & values

In [8]:
print(1 != 2) # not equal
print(3 != 3)
print(4 == 4) # equal to

True
False
True


- "==" operator compares the values and checks for value equality. 


In [9]:
day = 'Friday' # string
is_it_friday = True # bool

In [10]:
'Friday' == day

True

### Length

In [11]:
print(len(day)) # There are 6 characters in the word 'Friday'

6


In [12]:
print(len('day'))

3


### Length of a sentence

In [13]:
print(len('Ah, Welcome class!')) # space, symbols, numbers are counted as characters

18


### Strings

- can be declared with either single or double quotes

In [14]:
txt = "I need more and more holidays" 
# count method
x = txt.count("holidays") # returns a number equal to the number of occurrences of the word entered
y = txt.count("more")
print(x)
print(y)
# String concatenation
str_one = "city"
str_two = "PIT"
str_all = str_one + " : " + str_two
print(str_all)
print(len(str_all))
print(str_all[2])

# Operations on string
str_all_sorted = sorted(str_all)
print(str_all_sorted)
# Here is an example of sorting in the reverse direction
str_all_sorted_reverse = sorted(str_all, reverse = True)
print(str_all_sorted_reverse)

# Formatting
course_number = 24789
formatted = f"DL for Engineers: {course_number} ! " # Python 3.6+
formatted2 = "DL for Engineers: {} !".format(course_number) # Python 2 -> 3.5
print(formatted)
print(formatted2)
# Another way of printing the same sentence
print("DL for Engineers:",course_number, '!')

1
2
city : PIT
10
t
[' ', ' ', ':', 'I', 'P', 'T', 'c', 'i', 't', 'y']
['y', 't', 'i', 'c', 'T', 'P', 'I', ':', ' ', ' ']
DL for Engineers: 24789 ! 
DL for Engineers: 24789 !
DL for Engineers: 24789 !


# Lists

In [49]:
# Lists - can store anything
list_of_things = [] # Initializing an empty list

### 
list_of_things.append('aaa')
list_of_things.append('bbb')
list_of_things.append('ccc')
list_of_things.append('ddd')
###

# Accessing objects
print(type(list_of_things[3]))

# Print the list
print(list_of_things)

# Create another list
another_list = ['More objects', ['List inside a list!']]

# Merge the lists
third_lists = list_of_things + another_list
print(third_lists)

# Extend list_of_things
print('\nLength before adding another_list',len(list_of_things),'\n')
list_of_things.extend(another_list)
print('Length after adding another_list',len(list_of_things),'\n')

list_of_things+=another_list # list_of_things = list_of_things + another_list
print(list_of_things)


<class 'str'>
['aaa', 'bbb', 'ccc', 'ddd']
['aaa', 'bbb', 'ccc', 'ddd', 'More objects', ['List inside a list!']]

Length before adding another_list 4 

Length after adding another_list 6 

['aaa', 'bbb', 'ccc', 'ddd', 'More objects', ['List inside a list!'], 'More objects', ['List inside a list!']]


### List slicing and join

#### some_list[start : end : step]: like range but separated by colons

In [50]:
colors = ['red','blue','green','yellow','purple','indigo']
print(len(colors))
# Python indices start at 0
print(colors[0])
print(colors[:5])
print(colors[0:5])
print(colors[2:-1])
print(colors[2:])
print(colors[::2])
print(colors[::-1])
print(colors[5][::-1])

# Join (a string method)
words = ["Python","Is","Great"]
words =".".join(words)
print(words)


6
red
['red', 'blue', 'green', 'yellow', 'purple']
['red', 'blue', 'green', 'yellow', 'purple']
['green', 'yellow', 'purple']
['green', 'yellow', 'purple', 'indigo']
['red', 'green', 'purple']
['indigo', 'purple', 'yellow', 'green', 'blue', 'red']
ogidni
Python.Is.Great


### Boolean and condition

### if elif else
change the color to purple and red and run the code again

In [53]:
color = 'yellow'
if color == "purple":
    print("great choice")
elif color == "red":
    print("I like how you think")
elif color == "pink":
    print("not bad")
else:
    print('Thats new!')

Thats new!


# <font color='red'> Exercise:</font>
- age < 18 : cannot vote
- age => 18 : can vote

Code the above example, if age is less than 18, print cannot vote, otherwise print can vote 

### Looping

#### General Form :
#### for item in iterable_object:
      do something with item
    
- item is a new variable that you can call it whatever
- item references the current position of our iterator within the iterable

### Ranges

- A range is just a slice of number line.
- Ex: range (1,8) will give you integers from 1 to 7

In [ ]:
numbers = range(10)
print(list(numbers)) # It starts with zero and excludes the number 10
numbers = range(1,10)
print(list(numbers)) # It starts with one and excludes the number 10
odd = range(1,10,2) # start, end, step
print(list(odd)) #It starts with 1 and takes a step of 2
even = range(0,10,2) # start, end, step
print(list(even)) #It starts with 0 and takes a step of 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]
[0, 2, 4, 6, 8]


# <font color='red'>Exercise</font> 
Use a for loop to add up every odd number from 10 to 20 (inclusive)

In [16]:
add = 0

##Exercise: Use a for loop to add up every odd number from 10 to 20 (inclusive)






##
print('Sum of the numbers: ',add)     

11
13
15
17
19
Sum of the numbers:  75


In [57]:

numbers = range(10,20)
print(list(numbers)) # It starts with zero and excludes the number 10
i=0
while i<len(numbers):
    print('number is : ',numbers[i])
    print('but i is :',i)
    i=i+1




[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
number is :  10
but i is : 0
number is :  11
but i is : 1
number is :  12
but i is : 2
number is :  13
but i is : 3
number is :  14
but i is : 4
number is :  15
but i is : 5
number is :  16
but i is : 6
number is :  17
but i is : 7
number is :  18
but i is : 8
number is :  19
but i is : 9


### List Comprehension:

- A shorthand syntex that allows us to generate new list

Looping vs List Comprehension

In [ ]:
numbers = [1,2,3,4,5]
doubled_numbers = []

for num in numbers:
    doubled_numbers.append(num * 2)
    
print(doubled_numbers)

In [ ]:
numbers = [1,2,3,4,5]

doubled_numbers = [num * 2 for num in numbers]
    
print(doubled_numbers)

In [ ]:
numbers = [4,5,6,7,8,9,10]
evens = [num for num in numbers if num % 2 == 0]
odds = [num for num in numbers if num % 2 != 0]
print(evens, odds)

### Dictionaries

- A data structure that contains key-value pairs
- Keys and values are separated by colons
- Keys are almost always numnbers or strings
- Note: dictionary doesnt have a specific order, unlike a list

- update: Update keys and values in a dict with another set of key value pairs.

In [ ]:
first = dict(a=1,b=2,c=3,d=4)
second = {}
second.update(first)
print(second)
# Overwrite an existing ket
second["a"]= "AMAZING"
print(second)

In [ ]:
cmu = {
    'founder': "Andrew Carnegie",
    'private school?': True,
    'acceptance rate':0.2,
     4:"number of other campuses"
}
print(cmu)
print(cmu["founder"])
print(cmu["mascot"])

### Accessing all values in a dictionary

- Access value: Use .values()

In [ ]:
for value in cmu.values():
    print(value)

- Access key: Use .keys()

In [ ]:
for key in cmu.keys():
    print(key)

- Access both: .items()

In [ ]:
for key,value in cmu.items():
    print(key, ":", value)

- Test if a key exists: Use "in"

In [ ]:
print("founder" in cmu)
print("good sleep" in cmu)

### Dictionary Methods

- pop: Takes a single arguement corresponding to a ket and removes that key-value pair from the dict. Returns the value corresponding to the key that was removed.

In [ ]:
d = dict(a=1,b=2,c=3)
d.pop("a") # 1
d.pop() # TypeError: pop expected at least 1 arguement

## Introductory Example: Implementing with Lists 

To know the difference between an array and a list please Google ;)

This blog also provides a good explanation : https://medium.com/backticks-tildes/list-vs-array-python-data-type-40ac4f294551

In [1]:
# Inputs
# Now that we know what a list is lets use it to do a simple calculation
theta_1 = [[2, 1, 3],
     [1, 2, 3],
     [3, 1, 2]]

x = [7, 8, 5]
theta_0 = [1, 1, 1]

# Output
y = [0, 0, 0]



#  <font color='red'> Exercise </font> 
Computation of y = theta_1*x + theta_0 hint: you can use two FOR LOOPs  

In [ ]:
##### Computation of y = theta_1*x + theta_0  IKI TANE FOR LOOP YARATILMASI LAZIM







#####

# <font color='green'>What is NumPy?</font> 

If you have installed Anaconda correctly, Numpy should come with it. Just in case, if numpy is not installed please follow instructions at https://scipy.org/install.html

### NumPy-based Vectorized Implementation

In [2]:
import numpy as np

In [3]:
theta_1 = np.array([[2, 1, 3],
     [1, 2, 3],
     [3, 1, 2]])

theta_1, theta_1.shape

(array([[2, 1, 3],
        [1, 2, 3],
        [3, 1, 2]]),
 (3, 3))

In [4]:
x = np.array([7, 8, 5])
x.shape

(3,)

In [5]:
theta_0 = np.ones(3)
theta_0

array([1., 1., 1.])

In [6]:
theta_1.dot(x)

array([37, 38, 39])

In [7]:
np.matmul(theta_1,x)

array([37, 38, 39])

In [8]:
np.matmul(theta_1,x) + theta_0

array([38., 39., 40.])

In [9]:
theta_1@x + theta_0

array([38., 39., 40.])

## Multi-Dimensional Arrays

In [10]:
T = np.random.random((4,2,4)) # Creates an array of random numbers between 0 and 1 of the given shape
T

array([[[0.14980509, 0.450997  , 0.33427488, 0.16297464],
        [0.94887636, 0.7152355 , 0.65082539, 0.74092072]],

       [[0.04726837, 0.86000031, 0.93485077, 0.54660975],
        [0.58170265, 0.25526767, 0.39363011, 0.27766722]],

       [[0.37047987, 0.83059382, 0.7260046 , 0.58868834],
        [0.61310118, 0.52484631, 0.90382471, 0.03257181]],

       [[0.22013257, 0.18198093, 0.68079773, 0.99498777],
        [0.84923069, 0.74113169, 0.5017009 , 0.94336119]]])

### Random seed

In [ ]:
T = np.random.random((2,2)) # Creates an array of random numbers between 0 and 1 of the given shape
print(T)

np.random.seed(24878)
T = np.random.random((2,2)) # Now, all the random numbers are fixed as per the seed
print(T)

In [ ]:
np.random.seed(24878)
T = np.random.random((2,2))
print(T)

In [ ]:
W = T[1]
W.shape, W.dtype

In [ ]:
X = np.full((4,3), 24787, dtype=np.int32) # prints out the same in all dimension # remember it is a matrix multiplication for 2D 
X.shape, X.dtype,X

## Basic Element-wise Operations

In [ ]:
y = np.arange(5)
print(y, np.array(range(5)))

[0 1 2 3 4] [0 1 2 3 4]


In [ ]:
y == np.array(range(5))

array([ True,  True,  True,  True,  True])

In [ ]:
y + 1

array([1, 2, 3, 4, 5])

In [ ]:
y * 10

In [ ]:
(y + 1)**2

In [ ]:
y + y

In [ ]:
y / (y + 1)

In [ ]:
np.sqrt(y**2)

In [ ]:
np.max(y), np.min(y), np.sum(y)

## Indexing NumPy Arrays

In [ ]:
np.save('AI.npy', np.arange(16).reshape(4,4))

In [ ]:
T = np.load('AI.npy')
T,  T.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), (4, 4))

In [ ]:
T[0]

In [ ]:
T[1,0]  # more efficient version of T[1][0]# a similar approach can be used for N-d arrays 

In [ ]:
T[0,0:3] # selecting the specific elements for operations 

In [ ]:
(T % 10) == 0

In [ ]:
T[(T % 10) == 0] 

In [ ]:
np.minimum(T, 5)

In [ ]:
np.max(T)# please try np.maximum and by following the upper example

## Computation Along Axes

In [ ]:
A = np.random.random((2,2))
A

In [ ]:
A.sum()# all 

In [ ]:
np.sum(A)

In [ ]:
A.sum(axis=0) # column wise # col1 # col2 #col3

In [ ]:
np.sum(A, axis = 0)

In [ ]:
A.sum(axis=1) # row 1 

In [ ]:
np.sum(A, axis = 1)

In [ ]:
A.max(axis=0), A.argmax(axis=0)# column# the argmax returns the index where max occurs 

In [ ]:
np.max(A, axis = 0), np.argmax(A, axis = 0)

## Combining Arrays: Stacking & Concatenation

In [ ]:
a = np.full(3, 2)
b = np.full(3, 4)
c = np.full(3, 6)
print(a, b, c)

Stacking creates a new axis. It joins the supplied arrays, which must have the same shape, along that axis.
Indexing a single element from that axis returns the appropriate input array.

In [ ]:
B = np.stack([a, b, c], axis=1)
B, B.shape

In [ ]:
B = np.hstack((a, b, c))
B, B.shape

In [ ]:
B = np.vstack((a, b, c))
B, B.shape

In [ ]:
B[:,1]

Concatenating arrays joins them along an *existing* aixs.

In [ ]:
C = np.concatenate([B+10, B+50], axis=1 )
C

## Transposing and Reshaping

In [ ]:
C, C.shape

In [ ]:
CT = C.T
CT, CT.shape

In [ ]:
CR = C.reshape(9, 2)
CR, CR.shape # it goes row wise 

## Saving and Loading

### Saving and loading a single NumPy array

In [ ]:
# Save single array
x = np.random.random((5,))
print(x)

np.save('tmp.npy', x)

In [ ]:
# Load the array
y = np.load('tmp.npy')

print(y)

## Functions

Need to add parenthesis after the function name:

         def myfunction():

#### return: 

- Exits the function 

- Outputs whatever value is places after the return keyword

In [14]:
from random import random
def flip_coin():
    # generates random number 0-1
    r = random()
    if r > 0.5:
        result = "Heads"
    else: 
        result = "Tails"
    
    return result

flip_coin()

'Heads'

#### Accepting input parameters

In [ ]:
def double(d):

    return 2*d

double(10)

20

**bold text**### Default Parameters
- Allows you to be more defensive
- Avoids errors with incorrect parameters

In [ ]:
def add(a=10, b=20):
    return a+b
add()

30

### Keyworded Argument

*args: A special operator we can pass to functions. Gathers remaining arguments as a tuple.

This is just a parameter. You can call it whatever you want after the "*"!

Instead of doing:

     def sum_all_nums(num1, num2, num3, num4):
         return num1+num2+num3+num4

In [ ]:
def sum_all_nums(*args):
    total = 0
    for num in args:
        total += num
    return total

print(sum_all_nums(4,6,9,5,8))
print(sum_all_nums(4,6))

32
10


### Lambdas: like a function that has no name (anonymous function)

In [ ]:
def square(num): return num*num
square2 = lambda num: num*num # no return
print(square2(7))

49
